defaults:
  - exp: cube
  - _self_

project:
  seed: 1234
  name: NPSolver
  mode: train  # train or test
  continous_train: false
  device: cuda:0

output:
  name: ${model.name}_3_${now:%Y-%m-%d-%H-%M-%S}  # for train
  # name: ${model.name}_3_2026-06-08-10-46-00  # for test, set a fixed name to load the model
  path: /mnt/DEV_B/zengbocheng/NPSolver/${data.name}/${output.name}

hydra:
  run:
    dir: ${output.path}
