# @package _global_

data:
  name: control
  mesh_dir: /mnt/DEV_B/zengbocheng/FVMSolver/data/mesh/holes
  file_name: train_hole_mesh[N=100].h5
  sol_dir: /mnt/DEV_B/zengbocheng/FVMSolver/data/poisson
  test_files:
    - test_holes[N=10x10].h5
  size: 128
  dim: 2
  rms_f: false
  f_scale_mode: mean_power

model:
  name: ba-transolver
  space_dim: 2
  n_layers: 10
  n_hidden: 256
  dropout: 0.0
  n_head: 8
  mlp_ratio: 1
  fun_dim: 1
  bdry_dim: 5
  out_dim: 1
  slice_num: [64, 8]
  ref: 8
  unified_pos: false
  max_iter: 40
  scheme: 4
  omega: 0.1

params:
  lr: 0.0005
  start_epoch: 1
  num_epochs: 1000
  num_batches_per_epoch: 100
  batch_size: 8
  grad_norm: 1.0
  pct_start: 0.1
  save_freq: 2
  print_freq: 2
  batch_print_freq: 5
  num_workers: 4
  save_results: false